parameters:
    mfb_widget.service.class: MFB\WidgetBundle\Service\Widget
    mfb_widget.resources.class: MFB\WidgetBundle\Service\Resources
    mfb_widget.service.params:
      widgetWordCount: 10
      lastWordEnding: '...'

services:
    mfb_widget.service:
        class: %mfb_widget.service.class%
        arguments: ["@doctrine.orm.default_entity_manager", "@foxrate_base_widget.imagebuilder", '@service_container', %mfb_widget.service.params%]

    mfb_widget.resources:
        class: %mfb_widget.resources.class%
        arguments: ['@service_container']