mfb_reskribe:
    resource: "@MFBReskribeBundle/Resources/config/routing.yml"
    prefix:   /reskribe

mfb_widget:
    resource: "@MFBWidgetBundle/Resources/config/routing.yml"
    prefix:   /widget

mfb_account_profile:
    resource: "@MFBAccountProfileBundle/Resources/config/routing.yml"
    prefix:   /

mfb_feedback:
    resource: "@MFBFeedbackBundle/Resources/config/routing.yml"
    prefix:   /

mfb_account:
    resource: "@MFBAccountBundle/Resources/config/routing.yml"
    prefix:   /

mein_feedback_home:
    resource: "@MeinFeedbackHomeBundle/Resources/config/routing.yml"
    prefix:   /

mfb_admin:
  resource: "@MFBAdminBundle/Controller"
  type: annotation
  prefix: /admin

