mfb_account_profile:
    resource: "@MFBAccountProfileBundle/Resources/config/routing.yml"
    prefix:   /

mfb_feedback:
    resource: "@MFBFeedbackBundle/Resources/config/routing.yml"
    prefix:   /

mfb_admin:
    resource: "@MFBAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

mfb_account:
    resource: "@MFBAccountBundle/Resources/config/routing.yml"
    prefix:   /

mein_feedback_home:
    resource: "@MeinFeedbackHomeBundle/Resources/config/routing.yml"
    prefix:   /

