mfb_reskribe:
  resource: "@MFBReskribeBundle/Controller"
  type: annotation
  prefix: /reskribe

mfb_widget:
  resource: "@MFBWidgetBundle/Controller"
  type: annotation
  prefix: /widget

mfb_account_profile:
  resource: "@MFBAccountProfileBundle/Controller"
  type: annotation
  prefix: /

mfb_feedback:
  resource: "@MFBFeedbackBundle/Controller"
  type: annotation
  prefix: /

mfb_account:
  resource: "@MFBAccountBundle/Controller"
  type: annotation
  prefix: /

mein_feedback_home:
  resource: "@MeinFeedbackHomeBundle/Controller"
  type: annotation
  prefix: /

mfb_admin:
  resource: "@MFBAdminBundle/Controller"
  type: annotation
  prefix: /admin

