security:
    providers:
        main:
            entity:
                class: MFB\AccountBundle\Entity\Account
                property: email
    encoders:
            MFB\AccountBundle\Entity\Account: sha1
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    firewalls:
        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/admin/
            form_login:
                check_path: mfb_admin_login_check
                login_path: mfb_account_login
                use_referer: true
                default_target_path: mfb_admin_homepage
            logout:
                path:   mfb_admin_logout
                target: /

    access_control:
        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
