<?php

namespace MFB\FeedbackBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FeedbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackRepository extends EntityRepository
{
    public function getLastEnabledFeedbacks($accountId, $accountChannelId, $num = 4)
    {

        return $this->getEntityManager()->getRepository('MFBFeedbackBundle:Feedback')->findBy(
            array(
                'accountId' => $accountId,
                'channelId' => $accountChannelId,
                'isEnabled' => 1
            ),
            array('id'=>'DESC'),
            $num
        );
    }

    public function getFeedbackCount($accountChannelId)
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT COUNT(fb.id)
            FROM MFBFeedbackBundle:Feedback fb
            WHERE fb.channelId = ?1
            AND fb.isEnabled = 1'
        );

        $query->setParameter(1, $accountChannelId);
        return $query->getSingleScalarResult();
    }


}
