parameters:
  mfb_service.class: MFB\ServiceBundle\Service\Service
  mfb_service_type.class: MFB\ServiceBundle\Service\ServiceType
  mfb_service_provider.class: MFB\ServiceBundle\Service\ServiceProvider
  mfb_service_business.class: MFB\ServiceBundle\Service\Business
  mfb_service_definition.class: MFB\ServiceBundle\Service\ServiceDefinition

  mfb_service_provider.honorific:
    1: Mr
    2: Mrs
  mfb_service_business.defaults:
    1: {name: Service Providers, multiple: 0}
    2: {name: Sellers and Stores, multiple: 1}
    3: {name: Restaurants and Hotels, multiple: 0}
    4: {name: Producers, multiple: 1}
  mfb_service_types.defaults:
    1:
      - Lawyers
      - Medical practicioner
    2:
      - Car Seller
      - Grocery
      - Hardware
      - Bicycles
    3:
      - Restaurant
      - Hotel
    4:
      - Fashion
      - Clothes
      - Software

services:
  mfb_service.service:
    class: %mfb_service.class%
    arguments: ["@doctrine.orm.default_entity_manager", "@mfb_customer.service", "@mfb_service_provider.service", "@mfb_account_channel.service_type.service"]

  mfb_service_provider.service:
    class: %mfb_service_provider.class%
    arguments: ["@doctrine.orm.default_entity_manager", %mfb_service_provider.honorific%]

  mfb_service_business.service:
    class: %mfb_service_business.class%
    arguments: ["@doctrine.orm.default_entity_manager"]

  mfb_service_type.service:
    class: %mfb_service_type.class%
    arguments: ["@doctrine.orm.default_entity_manager"]

  mfb_service_definition.service:
    class: %mfb_service_definition.class%
    arguments: ["@doctrine.orm.default_entity_manager", "@mfb_account_channel.service"]
