parameters:
  mfb_service.class: MFB\ServiceBundle\Service\Service
  mfb_service_type.class: MFB\ServiceBundle\Service\ServiceType
  mfb_service_provider.class: MFB\ServiceBundle\Service\ServiceProvider
  mfb_service_business.class: MFB\ServiceBundle\Service\Business
  mfb_service_type_definition.class: MFB\ServiceBundle\Service\ServiceTypeDefinition

  mfb_service_provider.prefix:
    1: Mr
    2: Mrs

services:
  mfb_service.service:
    class: %mfb_service.class%
    arguments: ["@doctrine.orm.default_entity_manager", "@mfb_customer.service", "@mfb_service_provider.service", "@mfb_account_channel.service_type.service", @mfb_account_channel.service]

  mfb_service_provider.service:
    class: %mfb_service_provider.class%
    arguments: ["@doctrine.orm.default_entity_manager", %mfb_service_provider.prefix%, @mfb_account_channel.service]

  mfb_service_business.service:
    class: %mfb_service_business.class%
    arguments: ["@doctrine.orm.default_entity_manager"]

  mfb_service_type.service:
    class: %mfb_service_type.class%
    arguments: ["@doctrine.orm.default_entity_manager", @mfb_service_business.service]

  mfb_service_type_definition.service:
    class: %mfb_service_type_definition.class%
    arguments: ["@doctrine.orm.default_entity_manager"]


