parameters:
  mfb_service.class: MFB\ServiceBundle\Service\Service

services:
  mfb_service.service:
    class: %mfb_service.class%
    arguments: ["@doctrine.orm.default_entity_manager", "@mfb_customer.service"]