parameters:
#    mfb_account_profile.example.class: MFB\AccountProfileBundle\Example

services:
#    mfb_account_profile.example:
#        class: %mfb_account_profile.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
