mfb_admin_homepage:
    pattern:  /
    defaults: { _controller: MFBAdminBundle:Default:index }

mfb_admin_login_check:
    pattern: /login_check
    defaults: { _controller: MFBAdminBundle:Default:index }

mfb_admin_logout:
    pattern: /logout
    defaults: { _controller: MFBAdminBundle:Default:index }

mfb_location:
    pattern: /about_me
    defaults: { _controller: MFBAdminBundle:Default:location }

mfb_show_create_customer:
    pattern: /show_create_customer
    defaults: { _controller: MFBAdminBundle:Default:showCreateServiceCustomerForm }

mfb_save_customer:
    pattern: /save_customer
    defaults: { _controller: MFBAdminBundle:Default:saveServiceCustomer}

mfb_widget:
    pattern: /widget
    defaults: { _controller: MFBAdminBundle:Widget:index }

mfb_admin_select_variables:
    pattern: /select_variables
    defaults: { _controller: MFBAdminBundle:EmailTemplates:selectVariables}

mfb_admin_edit_email_template:
    pattern: /edit_template
    defaults: { _controller: MFBAdminBundle:EmailTemplates:edit }

mfb_admin_edit_thankyou_template:
    pattern: /edit_thankyou_template
    defaults: { _controller: MFBAdminBundle:EmailTemplates:thankYouEdit }

mfb_admin_list_possible_variables:
    pattern: /template/{emailTemplateId}/list_variables
    defaults: { _controller: MFBAdminBundle:EmailTemplates:listPossibleVariables }

mfb_feedback_enable:
    pattern: /enableFeedback/{feedbackId}
    defaults: { _controller: MFBAdminBundle:Default:enable}
    requirements: { _method: get }

mfb_feedback_enable:
    pattern: /enableFeedback/{feedbackId}
    defaults: { _controller: MFBAdminBundle:Widget:enable}
    requirements: { _method: get }

mfb_feedback_sort:
    pattern:  /sortFeedback
    defaults: { _controller: MFBAdminBundle:Widget:sort }
    requirements: { _method: post }

mfb_admin_success:
    pattern:  /success
    defaults: { _controller: MFBAdminBundle:Default:success }

mfb_admin_change_password:
    pattern: /changePassword
    defaults: { _controller: MFBAdminBundle:Default:changePassword }

mfb_admin_show_form_setup:
    pattern: /show_form_setup
    defaults: { _controller: MFBAdminBundle:FormSetup:show}

mfb_admin_save_service_group:
    pattern: /mfb_admin_save_service_group
    defaults: { _controller: MFBAdminBundle:FormSetup:saveServiceGroup}

mfb_admin_save_service_provider:
    pattern: /mfb_admin_save_service_provider
    defaults: { _controller: MFBAdminBundle:FormSetup:saveServiceProvider}

mfb_admin_update_service_visibility:
    pattern: /mfb_admin_update_service_visibility
    defaults: { _controller: MFBAdminBundle:FormSetup:updateServicesVisibility}