mfb_admin_homepage:
    pattern:  /
    defaults: { _controller: MFBAdminBundle:Default:index }

mfb_admin_login_check:
    pattern: /login_check
    defaults: { _controller: MFBAdminBundle:Default:index }

mfb_admin_logout:
    pattern: /logout
    defaults: { _controller: MFBAdminBundle:Default:index }

mfb_location:
    pattern: /about_me
    defaults: { _controller: MFBAdminBundle:Default:location }

mfb_show_create_customer:
    pattern: /show_create_customer
    defaults: { _controller: MFBAdminBundle:Default:index }

mfb_save_customer:
    pattern: /save_customer
    defaults: { _controller: MFBAdminBundle:Default:saveServiceCustomer}

mfb_save_feedback_activation:
    pattern: /save_feedback_activation
    defaults: { _controller: MFBAdminBundle:Default:saveFeedbackActivation}
    requirements: { _method: POST }

mfb_widget:
    pattern: /widget
    defaults: { _controller: MFBAdminBundle:Widget:index }

mfb_admin_select_variables:
    pattern: /select_variables
    defaults: { _controller: MFBAdminBundle:Templates:selectVariables}

mfb_admin_edit_template:
    pattern: /edit_template
    defaults: { _controller: MFBAdminBundle:Templates:edit }

mfb_admin_edit_thankyou_template:
    pattern: /edit_thankyou_template
    defaults: { _controller: MFBAdminBundle:Templates:thankYouEdit }

mfb_admin_list_possible_variables:
    pattern: /template/{emailTemplateId}/list_variables
    defaults: { _controller: MFBAdminBundle:Templates:listPossibleVariables }

mfb_feedback_enable:
    pattern: /enableFeedback/{feedbackId}
    defaults: { _controller: MFBAdminBundle:Default:enable}
    requirements: { _method: get }

mfb_feedback_enable:
    pattern: /enableFeedback/{feedbackId}
    defaults: { _controller: MFBAdminBundle:Widget:enable}
    requirements: { _method: get }

mfb_feedback_sort:
    pattern:  /sortFeedback
    defaults: { _controller: MFBAdminBundle:Widget:sort }
    requirements: { _method: post }

mfb_admin_success:
    pattern:  /success
    defaults: { _controller: MFBAdminBundle:Default:success }

mfb_admin_change_password:
    pattern: /changePassword
    defaults: { _controller: MFBAdminBundle:Default:changePassword }

mfb_admin_show_form_setup:
    pattern: /show_form_setup
    defaults: { _controller: MFBAdminBundle:FormSetup:show}

mfb_admin_save_service_group:
    pattern: /admin_save_service_group
    defaults: { _controller: MFBAdminBundle:FormSetup:saveServiceGroup}

mfb_admin_save_service_provider:
    pattern: /admin_save_service_provider
    defaults: { _controller: MFBAdminBundle:FormSetup:saveServiceProvider}

mfb_admin_update_service_visibility:
    pattern: /admin_update_service_visibility
    defaults: { _controller: MFBAdminBundle:FormSetup:updateServicesVisibility}

mfb_admin_update_rating_criteria_select:
    pattern: /admin_update_rating_criteria_select
    defaults: { _controller: MFBAdminBundle:FormSetup:updateRatingCriteriaSelect}
mfb_admin_images_show:
    pattern: /admin_images_show
    defaults: { _controller: MFBAdminBundle:Image:show }

mfb_admin_image_save_logo:
    pattern: /admin_image_save_logo
    defaults: { _controller: MFBAdminBundle:Image:saveLogo }

mfb_admin_image_remove_logo:
    pattern: /admin_image_remove_logo
    defaults: { _controller: MFBAdminBundle:Image:removeLogo }

mfb_admin_setup_select_business:
    pattern: /admin_setup_select_business
    defaults: { _controller: MFBAdminBundle:SetupWizard:selectBusiness }

mfb_admin_setup_select_single_service:
    pattern: /admin_setup_select_single_service/{businessId}
    defaults: { _controller: MFBAdminBundle:SetupWizard:selectSingleServiceType }
    requirements:
      businessId: \d+

mfb_admin_setup_select_multiple_service:
    pattern: /admin_setup_select_multiple_service/{businessId}
    defaults: { _controller: MFBAdminBundle:SetupWizard:selectMultipleServiceType }
    requirements:
      businessId: \d+

mfb_admin_setup_insert_definitions:
    pattern: /admin_setup_insert_definitions
    defaults: { _controller: MFBAdminBundle:SetupWizard:insertDefinitions }

mfb_admin_setup_remove_definitions:
    pattern: /admin_setup_remove_definitions/{definitionId}
    defaults: { _controller: MFBAdminBundle:SetupWizard:removeDefinitions }
    requirements:
      definitionId: \d+
