mfb_admin_homepage:
    pattern:  /
    defaults: { _controller: MFBAdminBundle:Default:index }

mfb_admin_login_check:
    pattern: /login_check
    defaults: { _controller: MFBAdminBundle:Default:index }

mfb_admin_logout:
    pattern: /logout
    defaults: { _controller: MFBAdminBundle:Default:index }

mfb_location:
    pattern: /about_me
    defaults: { _controller: MFBAdminBundle:Default:location }

mfb_add_customer:
    pattern: /add_customer
    defaults: { _controller: MFBAdminBundle:Default:customer }

mfb_admin_edit_email_template:
    pattern: /edit_template
    defaults: { _controller: MFBAdminBundle:EmailTemplates:edit }

mfb_admin_list_possible_variables:
    pattern: /template/{emailTemplateId}/list_variables
    defaults: { _controller: MFBAdminBundle:EmailTemplates:listPossibleVariables }

mfb_admin_add_variable:
    pattern: /template/{emailTemplateId}/add_variable/{variableType}
    defaults: { _controller: MFBAdminBundle:EmailTemplates:addVariable }

