parameters:
#    mfb_admin.example.class: MFB\AdminBundle\Example


services:
    my_locale_listener:
        class: MFB\AdminBundle\LocaleListener
        arguments:
            hostMap:
                default: de
                miofeedback.it: it
                meinfeedback.net: de
        tags:
            -  { name: kernel.event_subscriber }