parameters:
  mfb_admin.form_setup.class: MFB\AdminBundle\Service\FormSetup
  mfb_admin.form_setup.steps.class: MFB\AdminBundle\Service\FormSetupSteps
  mfb_admin.form_setup.allowed.actions:
            - 'mfb_admin_update_rating_criteria_select'
            - 'mfb_admin_save_service_provider'
            - 'mfb_admin_update_service_visibility'
  mfb_admin.form_setup.allowed.controllers:
            - 'MFB\AdminBundle\Controller\SetupWizardController'

  mfb_admin.form_setup.redirect: 'mfb_admin_setup_select_business'

  mfb_admin.form_setup.after_setup: 'mfb_admin_homepage'

  mfb_admin.form_setup.steps:
    1: mfb_admin_setup_select_business
    2: mfb_admin_setup_select_service
    3: mfb_admin_setup_insert_definitions
    4: mfb_admin_setup_select_criterias
    5: mfb_admin_setup_insert_service_provider
    6: mfb_admin_setup_account_settings


services:
  mfb_admin.form_setup.service:
    class: %mfb_admin.form_setup.class%
    arguments: [@mfb_account_channel.rating_criteria.service, @mfb_account_channel.service_type.service, @mfb_account_channel.service, @mfb_channel_definition.service, @mfb_service_provider.service]

  my_locale_listener:
      class: MFB\AdminBundle\LocaleListener
      arguments:
          hostMap:
              default: en
              miofeedback.it: it
              meinfeedback.net: en
      tags:
          -  { name: kernel.event_subscriber }
  kernel.listener.LoggedInAdminListener:
      class: MFB\AdminBundle\EventListener\LoggedInAdminListener
      arguments: [@router, @security.context, @mfb_admin.form_setup.service, %mfb_admin.form_setup.allowed.actions%, %mfb_admin.form_setup.allowed.controllers%, %mfb_admin.form_setup.redirect%, @mfb_account_channel.service]
      tags:
        - {name: kernel.event_listener, event: kernel.request, method: onKernelRequest}

  mfb_admin.form_setup.steps.service:
    class: %mfb_admin.form_setup.steps.class%
    arguments: [%mfb_admin.form_setup.steps%, %mfb_admin.form_setup.after_setup%]
