parameters:
#    mfb_admin.example.class: MFB\AdminBundle\Example


services:
    my_locale_listener:
        class: MFB\AdminBundle\LocaleListener
        arguments:
            hostMap:
                default: de
                miofeedback.it: it
                meinfeedback.net: de
        tags:
            -  { name: kernel.event_subscriber }
    kernel.listener.LoggedInAdminListener:
        class: MFB\AdminBundle\EventListener\LoggedInAdminListener
        arguments: [@router, @security.context, @mfb_account_channel.rating_criteria.service]
        tags:
          - {name: kernel.event_listener, event: kernel.request, method: onKernelRequest}
