parameters:
#    mfb_admin.example.class: MFB\AdminBundle\Example

services:
#    mfb_admin.example:
#        class: %mfb_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
