parameters:
  mfb_admin.form_setup.class: MFB\AdminBundle\Service\FormSetup
  mfb_admin.form_setup.steps.class: MFB\AdminBundle\Service\FormSetupSteps
  mfb_admin.wizard_step.business.class: MFB\AdminBundle\Service\SetupWizardSteps\Business
  mfb_admin.wizard_step.serviceType.class: MFB\AdminBundle\Service\SetupWizardSteps\ServiceType
  mfb_admin.wizard_step.serviceType.class: MFB\AdminBundle\Service\SetupWizardSteps\ServiceType
  mfb_admin.wizard_step.serviceDefinition.class: MFB\AdminBundle\Service\SetupWizardSteps\ServiceDefinition
  mfb_admin.wizard_step.serviceCriterias.class: MFB\AdminBundle\Service\SetupWizardSteps\ServiceCriterias
  mfb_admin.wizard_step.serviceProvider.class: MFB\AdminBundle\Service\SetupWizardSteps\ServiceProvider
  mfb_admin.wizard_step.accountSettings.class: MFB\AdminBundle\Service\SetupWizardSteps\AccountSettings
  mfb_admin.wizard_step.finished.class: MFB\AdminBundle\Service\SetupWizardSteps\Finished

  mfb_admin.form_setup.allowed.actions:
            - 'mfb_admin_update_rating_criteria_select'
            - 'mfb_admin_save_service_provider'
            - 'mfb_admin_update_service_visibility'
  mfb_admin.form_setup.allowed.controllers:
            - 'MFB\AdminBundle\Controller\SetupWizardController'

  mfb_admin.form_setup.redirect: 'mfb_admin_setup_wizard'

services:
  mfb_admin.form_setup.service:
    class: %mfb_admin.form_setup.class%
    arguments: [@mfb_account_channel.rating_criteria.service, @mfb_account_channel.service_type.service, @mfb_account_channel.service, @mfb_channel_definition.service, @mfb_service_provider.service]

  my_locale_listener:
      class: MFB\AdminBundle\LocaleListener
      arguments:
          hostMap:
              default: en
              miofeedback.it: it
              meinfeedback.net: en
      tags:
          -  { name: kernel.event_subscriber }
  kernel.listener.LoggedInAdminListener:
      class: MFB\AdminBundle\EventListener\LoggedInAdminListener
      arguments: [@router, @security.context, @mfb_admin.form_setup.service, %mfb_admin.form_setup.allowed.actions%, %mfb_admin.form_setup.allowed.controllers%, %mfb_admin.form_setup.redirect%, @mfb_account_channel.service]
      tags:
        - {name: kernel.event_listener, event: kernel.request, method: onKernelRequest}

  mfb_admin.wizard_step.business.service:
    class: %mfb_admin.wizard_step.business.class%
    arguments: [@mfb_setup_wizard.step.service]
    tags:
       - {name: mfb_setup_wizard.steps}


  mfb_admin.wizard_step.serviceType.service:
    class: %mfb_admin.wizard_step.serviceType.class%
    arguments: [@mfb_setup_wizard.step.service]
    tags:
       - {name: mfb_setup_wizard.steps}

  mfb_admin.wizard_step.serviceDefinition.service:
    class: %mfb_admin.wizard_step.serviceDefinition.class%
    arguments: [@mfb_setup_wizard.step.service]
    tags:
       - {name: mfb_setup_wizard.steps}

  mfb_admin.wizard_step.serviceCriterias.service:
    class: %mfb_admin.wizard_step.serviceCriterias.class%
    arguments: [@mfb_setup_wizard.step.service]
    tags:
       - {name: mfb_setup_wizard.steps}

  mfb_admin.wizard_step.serviceProvider.service:
    class: %mfb_admin.wizard_step.serviceProvider.class%
    arguments: [@mfb_setup_wizard.step.service]
    tags:
       - {name: mfb_setup_wizard.steps}

  mfb_admin.wizard_step.accountSettings.service:
    class: %mfb_admin.wizard_step.accountSettings.class%
    arguments: [@mfb_setup_wizard.step.service]
    tags:
       - {name: mfb_setup_wizard.steps}

  mfb_admin.wizard_step.finished.service:
    class: %mfb_admin.wizard_step.finished.class%
    arguments: [@mfb_setup_wizard.step.service]
    tags:
       - {name: mfb_setup_wizard.steps}
