parameters:
#    mfb_rating.example.class: MFB\RatingBundle\Example

services:
#    mfb_rating.example:
#        class: %mfb_rating.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
