parameters:
    mfb_rating.default.ratings:
      - Speed
      - Price
      - Delivery
      - Quality
      - Service

services:
#    mfb_rating.example:
#        class: %mfb_rating.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
