parameters:
    mfb_rating.class: MFB\RatingBundle\Service\Rating
    mfb_rating.boundary:
      min: 1
      max: 5

services:
    mfb_rating.service:
        class: %mfb_rating.class%
        arguments: ["@doctrine.orm.default_entity_manager"]
