parameters:
    mfb_rating.boundary:
      min: 1
      max: 5

services:
#    mfb_rating.example:
#        class: %mfb_rating.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
