parameters:
#    mfb_document.example.class: MFB\DocumentBundle\Example

services:
#    mfb_document.example:
#        class: %mfb_document.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
