parameters:
    mfb_country.default.countries:
      - Germany
      - Spain
      - France

services:
#    mfb_country.example:
#        class: %mfb_country.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
