parameters:
    mfb_country.class: MFB\CountryBundle\Service\Country
    mfb_country.default.countries:
      - Germany
      - Spain
      - France
      - Italy
      - United Kingdom

services:
    mfb_country.service:
        class: %mfb_country.class%
        arguments: ["@doctrine.orm.default_entity_manager"]
