parameters:
#    mfb_country.example.class: MFB\CountryBundle\Example

services:
#    mfb_country.example:
#        class: %mfb_country.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
