parameters:
     mfb_account_channel.account.class: MFB\ChannelBundle\Entity\AccountChannel
     mfb_account_channel.class: MFB\ChannelBundle\Service\Channel
     mfb_account_channel.service_type.class: MFB\ChannelBundle\Service\ChannelServiceType
     mfb_account_channel.rating_criteria.class: MFB\ChannelBundle\Service\ChannelRatingCriteria
     mfb_account_channel.rating_criteria.limit: 3
     mfb_channel_definition.class: MFB\ChannelBundle\Service\ChannelServiceDefinition

services:
     mfb_account_channel.service:
        class: %mfb_account_channel.class%
        arguments: ["@doctrine.orm.default_entity_manager", "@mfb_country.service"]

     mfb_account_channel.rating_criteria.service:
        class: %mfb_account_channel.rating_criteria.class%
        arguments: ["@doctrine.orm.default_entity_manager", "%mfb_account_channel.rating_criteria.limit%", "@mfb_account_channel.service_type.service", "@mfb_account_channel.service"]

     mfb_account_channel.service_type.service:
       class: %mfb_account_channel.service_type.class%
       arguments: ["@doctrine.orm.default_entity_manager", @mfb_account_channel.service, @mfb_service_type.service]

     mfb_channel_definition.service:
       class: %mfb_channel_definition.class%
       arguments: ["@doctrine.orm.default_entity_manager", "@mfb_account_channel.service"]
