parameters:
#    mfb_channel.example.class: MFB\ChannelBundle\Example

services:
#    mfb_channel.example:
#        class: %mfb_channel.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
