parameters:
     mfb_account_channel.account.class: MFB\ChannelBundle\Entity\AccountChannel
     mfb_account_channel.manager.class: MFB\ChannelBundle\Entity\AccountChannelManager

services:
     mfb_account_channel.manager:
        class: %mfb_account_channel.manager.class%
        factory_service: "doctrine.orm.default_entity_manager"
        factory_method: "getRepository"
        arguments: ["%mfb_account_channel.account.class%"]
