parameters:
    mfb_email.sender.class: MFB\EmailBundle\Service\Sender
    mfb_email.variables.class: MFB\EmailBundle\Service\Variables

services:
    mfb_email.sender:
        class: %mfb_email.sender.class%
        arguments: [@mailer, @templating, @router, @translator]

    mfb_email.variables:
        class: %mfb_email.variables.class%
        arguments: [@translator]
#        arguments: [@service_id, "plain_value", %parameter%]
