mfb_feedback_create:
    pattern:  /createFeedback/{accountId}
    defaults: { _controller: MFBFeedbackBundle:Default:index }

mfb_feedback_save:
    pattern:  /saveFeedback/{accountId}/{accountChannelId}
    defaults: { _controller: MFBFeedbackBundle:Default:save }
    requirements: { _method: post }

mfb_feedback_create_with_invite:
    pattern:  /createFeedback/invite/{token}
    defaults: { _controller: MFBFeedbackBundle:Invite:index }

mfb_feedback_save_with_invite:
    pattern:  /saveFeedback/invite/{token}
    defaults: { _controller: MFBFeedbackBundle:Invite:save }
    requirements: { _method: post }
