mfb_feedback_create_with_invite:
    pattern:  /createFeedback/{token}
    defaults: { _controller: MFBFeedbackBundle:Default:index }

mfb_feedback_save_with_invite:
    pattern:  /saveFeedback/{token}
    defaults: { _controller: MFBFeedbackBundle:Default:save }
    requirements: { _method: post }
