parameters:
#    mfb_feedback.example.class: MFB\FeedbackBundle\Example

services:
#    mfb_feedback.example:
#        class: %mfb_feedback.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
