MFB\FeedbackBundle\Entity\Feedback:
  properties:
    feedbackRating:
      - Valid: ~

MFB\FeedbackBundle\Entity\FeedbackRating:
  properties:
    rating:
      - MFB\FeedbackBundle\Validator\Constraints\RatingMaxBounds: ~
      - MFB\FeedbackBundle\Validator\Constraints\RatingMinBounds: ~