MFB\FeedbackBundle\Entity\Feedback:
  properties:
    feedbackRating:
      - Valid: ~


MFB\FeedbackBundle\Entity\FeedbackRating:
  properties:
    rating:
      - GreaterThanOrEqual :
          value: 1
          message: "Not all star ratings were selected"
      - LessThanOrEqual :
          value: 5
          message: "The rating is too big"