MFB\FeedbackBundle\Entity\Feedback:
  properties:
    feedbackRating:
      - Valid: ~


MFB\FeedbackBundle\Entity\FeedbackRating:
  properties:
    rating:
      - GreaterThan :
          value: 0
          message: "Not all star ratings were selected"