mfb_account_login:
    pattern:  /login
    defaults: { _controller: MFBAccountBundle:Default:index }

mfb_account_login_check:
    pattern:  /login_check
    defaults: { _controller: MFBAccountBundle:Default:index }

mfb_account_register:
    pattern: /register
    defaults: { _controller: MFBAccountBundle:Register:index }

mfb_account_create:
    pattern:  /create
    defaults: { _controller: "MFBAccountBundle:Register:create" }
    requirements: { _method: post }
