mfb_account_login:
    pattern:  /login
    defaults: { _controller: MFBAccountBundle:Default:index }

mfb_account_register:
    pattern: /register
    defaults: { _controller: MFBAccountBundle:Register:index }
