parameters:
     mfb_account.account.class: MFB\AccountBundle\Entity\Account
     mfb_account.manager.class: MFB\AccountBundle\Entity\AccountManager

services:
     mfb_account.manager:
        class: %mfb_account.manager.class%
        factory_service: "doctrine.orm.default_entity_manager"
        factory_method: "getRepository"
        arguments: ["%mfb_account.account.class%"]