parameters:
#    mfb_customer.example.class: MFB\CustomerBundle\Example

services:
#    mfb_customer.example:
#        class: %mfb_customer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
