parameters:
    mfb_customer.event_listener.new_customer.class: MFB\CustomerBundle\EventListener\NewCustomerListener

services:
    mfb_customer.listener.new_customer:
        class: %mfb_customer.event_listener.new_customer.class%
        arguments: ["@doctrine.orm.default_entity_manager", "@mfb_email.sender", "@translator"]
        tags:
            - { name: kernel.event_listener, event: customer.create.complete, method: onCreateCustomerComplete}