parameters:
#    mein_feedback_home.example.class: MeinFeedback\HomeBundle\Example

services:
#    mein_feedback_home.example:
#        class: %mein_feedback_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
