mfb_reskribe_homepage:
    pattern:  /callback
    defaults: { _controller: MFBReskribeBundle:Default:index }
    requirements: { _method: post }

mfb_reskribe_homepage:
    pattern:  /success
    defaults: { _controller: MFBReskribeBundle:Default:success }
