parameters:
    mfb_reskribe.api.class: MFB\ReskribeBundle\Service\Api
    mfb_reskribe.token: "d1951ed66baa05e70319c1ce1c850086"

services:
    mfb_reskribe.api:
        class: %mfb_reskribe.api.class%
        arguments: [@doctrine.orm.default_entity_manager, @buzz, %mfb_reskribe.token%]
