parameters:
#    mfb_reskribe.example.class: MFB\ReskribeBundle\Example

services:
#    mfb_reskribe.example:
#        class: %mfb_reskribe.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
