parameters:
    mfb_reskribe.api.class: MFB\ReskribeBundle\Service\Api
    mfb_reskribe.token: "6zrqfmnwzjosgyf2wzxltanius4ozqbfkek__fpdd9nqc4j5ux88quwm5k84jobdha"

services:
    mfb_reskribe.api:
        class: %mfb_reskribe.api.class%
        arguments: [@doctrine.orm.default_entity_manager, @buzz, %mfb_reskribe.token%]
