parameters:
    mfb_setup_wizard.class: MFB\SetupWizardBundle\Service\SetupWizard
    mfb_setup_wizard.step.class: MFB\SetupWizardBundle\Service\WizardStep
    mfb_setup_wizard.configurator.class: MFB\SetupWizardBundle\Service\Configurator

    mfb_setup_wizard.step.status:
      pending: 1
      complete: 2
      inactive: 3

services:
    mfb_setup_wizard.service:
        class: %mfb_setup_wizard.class%
        arguments: [@mfb_setup_wizard.step.service, @router, @mfb_setup_wizard.configurator.service, @event_dispatcher]

    mfb_setup_wizard.configurator.service:
      class: %mfb_setup_wizard.configurator.class%
      arguments: [@event_dispatcher, @mfb_setup_wizard.step.service]

    mfb_setup_wizard.step.service:
      class: %mfb_setup_wizard.step.class%
      arguments: [@doctrine.orm.default_entity_manager, %mfb_setup_wizard.step.status%, @mfb_account_channel.service]
